# Generated by Django 4.2.5 on 2023-09-24 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kategoriya')),
                ('bg_image', models.FileField(upload_to='cat/')),
                ('icon', models.FileField(blank=True, null=True, upload_to='cat/')),
                ('image', models.FileField(upload_to='cat/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='mehsul adi')),
                ('image', models.FileField(upload_to='product/', verbose_name='mehsulun shekli')),
                ('credit', models.BooleanField(default=False)),
                ('garanty', models.IntegerField(default=12, verbose_name='zemanet')),
                ('price', models.IntegerField(verbose_name='qiymet')),
                ('discount', models.IntegerField(verbose_name='Endriim faizi')),
                ('about', models.TextField(verbose_name='haqqinda')),
                ('rating', models.FloatField(default=5, verbose_name='rating')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category', verbose_name='kategoriya adi')),
            ],
        ),
    ]
