# Generated by Django 4.2.5 on 2023-09-24 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ekran_width', models.FloatField(verbose_name='ekran olcusu')),
                ('memory', models.IntegerField(verbose_name='yaddas')),
                ('ram', models.IntegerField(verbose_name='operativ  yaddas')),
                ('main_camera', models.IntegerField(verbose_name='arxa kamera')),
                ('front_camera', models.IntegerField(verbose_name='qabaq kamera')),
                ('color', models.CharField(choices=[('Ag', 'Ag'), ('Qara', 'Qara'), ('Mavi', 'Mavi')], max_length=100, verbose_name='rengi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.product', verbose_name='product adi')),
            ],
        ),
    ]
