# Generated by Django 4.2.5 on 2023-09-26 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0003_remove_phone_product_remove_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='kategoriya')),
                ('bg_color', models.FileField(upload_to='cat/')),
                ('icon', models.FileField(blank=True, null=True, upload_to='cat/')),
                ('image', models.FileField(upload_to='cat/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='mehsul adi')),
                ('image', models.FileField(upload_to='product/')),
                ('price', models.FloatField(verbose_name='qiymet')),
                ('discount', models.IntegerField(verbose_name='endirim faizi')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Haqqinda')),
                ('garanty', models.IntegerField(default=12)),
                ('credit', models.BooleanField(default=False, verbose_name='Kredit')),
                ('rating', models.FloatField(default=5.0, verbose_name='reytinq')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category', verbose_name='kategoriya adi')),
            ],
        ),
    ]
