# Generated by Django 4.2.5 on 2023-09-27 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0006_remove_phone_product_remove_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Kategoriya adi')),
                ('bg_image', models.FileField(upload_to='cat/', verbose_name='arxa shekli')),
                ('icon', models.FileField(blank=True, null=True, upload_to='cat/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='mehsulun adi')),
                ('price', models.FloatField(verbose_name='qiymeti')),
                ('garanty', models.IntegerField(default=12, verbose_name='zemanet')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Endirim faizi')),
                ('credit', models.BooleanField(default=False, verbose_name='Kredit')),
                ('image', models.FileField(upload_to='', verbose_name='Shekli')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category', verbose_name='kategoriyasi')),
            ],
        ),
    ]
