# Generated by Django 4.2.5 on 2023-09-27 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.FloatField(verbose_name='ekran olcusu')),
                ('memory', models.IntegerField(verbose_name='Yaddas')),
                ('ram', models.IntegerField(verbose_name='operativ yaddas')),
                ('main_cam', models.IntegerField(verbose_name='Arxa kamera')),
                ('add_cam', models.IntegerField(verbose_name='Arxa kamera')),
                ('color', models.CharField(choices=[('Ag', 'Ag'), ('Qara', 'Qara'), ('Mavi', 'Mavi')], max_length=100, verbose_name='rengi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.product', verbose_name='mehsul')),
            ],
        ),
    ]
