# Generated by Django 4.2.5 on 2023-09-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0009_remove_phone_product_remove_product_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kateqoriya adı')),
                ('bg_image', models.FileField(upload_to='', verbose_name='Fon(Arxa) şəkli')),
                ('icon', models.FileField(blank=True, null=True, upload_to='', verbose_name='Ikon şəkli')),
                ('image', models.FileField(upload_to='', verbose_name='Şəkil')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
