# Generated by Django 4.2.5 on 2023-09-28 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Məhsulun adı')),
                ('price', models.FloatField(verbose_name='Qiyməti')),
                ('about', models.TextField(blank=True, null=True, verbose_name='Haqqında')),
                ('discount', models.IntegerField(verbose_name='Endirim faizi')),
                ('credit', models.BooleanField(default=False, verbose_name='kredit')),
                ('garanty', models.IntegerField(default=12, verbose_name='Zəmanət')),
                ('rating', models.FloatField(default=5, verbose_name='Reytinq')),
                ('image', models.FileField(upload_to='', verbose_name='Şəkil')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.category', verbose_name='Kateqoriyası')),
            ],
        ),
    ]
