# Generated by Django 4.2.5 on 2023-09-28 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.FloatField(verbose_name='Ekran ölçüsü')),
                ('main_cam', models.IntegerField(blank=True, null=True, verbose_name='Əsas kamera')),
                ('add_cam', models.IntegerField(blank=True, null=True, verbose_name='Ön kamera')),
                ('battery', models.IntegerField(verbose_name='Batareya(mAH)')),
                ('biometric', models.BooleanField(verbose_name='Üz tanıma')),
                ('memory', models.IntegerField(verbose_name='Yaddaş')),
                ('ram', models.IntegerField(verbose_name='Operativ yaddaş')),
                ('network', models.CharField(max_length=100, verbose_name='Şəbəkə')),
                ('color', models.CharField(choices=[('Ağ', 'Ağ'), ('Qara', 'Qara'), ('Mavi', 'Mavi')], max_length=100, verbose_name='Rəngi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.product', verbose_name='Məhsulun adı')),
            ],
        ),
    ]
