# Generated by Django 4.2.5 on 2023-09-30 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_specialshop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='shekil')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.product')),
            ],
        ),
    ]
