# Generated by Django 4.2.5 on 2023-09-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_remove_product_image_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialshop',
            name='image',
            field=models.ImageField(upload_to='special/'),
        ),
        migrations.AlterField(
            model_name='specialshop',
            name='link',
            field=models.TextField(verbose_name='Url'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
