# Generated by Django 4.2.5 on 2023-09-30 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_specialshop_image_alter_specialshop_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/', verbose_name='shekli')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.product')),
            ],
        ),
    ]
