# Generated by Django 4.2.5 on 2023-10-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_notebook'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notebook',
        ),
    ]
