# Generated by Django 4.2.5 on 2023-10-10 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
