# Generated by Django 4.2.5 on 2023-10-15 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0029_product_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='subuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profil/')),
                ('phone', models.CharField(max_length=10)),
                ('tip', models.CharField(choices=[('Sirket', 'Sirket'), ('Ferdi', 'Ferdi'), ('Magaza', 'Magaza')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Istifadeci adi')),
            ],
        ),
    ]
