# Generated by Django 4.2.5 on 2023-10-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_subuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='subuser',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='haqqinda'),
        ),
    ]
