# Generated by Django 4.2.5 on 2023-10-16 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0033_product_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='subuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/')),
                ('text', models.TextField()),
                ('phone', models.CharField(max_length=10)),
                ('usertype', models.CharField(choices=[('Magaza', 'Magaza'), ('Ferdi', 'Ferdi'), ('Shirket', 'Shirket')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
