# Generated by Django 4.2.5 on 2023-10-17 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0036_product_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profil/')),
                ('phone', models.CharField(max_length=10)),
                ('adres', models.CharField(max_length=100)),
                ('about', models.TextField(verbose_name='Haqqında')),
                ('usertype', models.CharField(max_length=50, verbose_name='Istifadəçinin tipi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Istifadəçi')),
            ],
        ),
    ]
