# Generated by Django 4.2.5 on 2023-10-17 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0037_subuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subuser',
            name='usertype',
        ),
    ]
