# Generated by Django 4.2.5 on 2023-10-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0042_alter_images_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Ağ', 'Ağ'), ('Qara', 'Qara'), ('Mavi', 'Mavi')], default=1, max_length=100, verbose_name='Rəngi'),
            preserve_default=False,
        ),
    ]
