# Generated by Django 4.2.5 on 2023-10-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0043_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
    ]
